### ISSUE TITLE
Maximum recursion depth exceeded in cmp in build()

### ISSUE THREAD

**Issue by markol** [jmplonka/InventorLoader#13]
Problem occurs with some specific files (sample [test.zip](https://github.com/jmplonka/InventorLoader/files/2130231/test.zip) enclosed). Setting recursion limit does not help, fast temporary fix is possible by adding counter variables to break recursion, like:

```
maxRecursion = 500
...
global counter
	if (self.type == 'ref' and counter < maxRecursion):
``` 

```
  File "~/.FreeCAD/Mod/InventorLoader/Acis.py", line 2857, in build
    self.shape = self.surface.build()
  File "~/.FreeCAD/Mod/InventorLoader/Acis.py", line 2857, in build
    self.shape = self.surface.build()
  File "~/.FreeCAD/Mod/InventorLoader/Acis.py", line 2857, in build
    self.shape = self.surface.build()
  File "~/.FreeCAD/Mod/InventorLoader/Acis.py", line 2857, in build
    self.shape = self.surface.build()
  File "~/.FreeCAD/Mod/InventorLoader/Acis.py", line 2857, in build
    self.shape = self.surface.build()<type 'exceptions.RuntimeError'>: maximum recursion depth exceeded in cmp```

**Comment by jmplonka** [comment]
Hi!
Thank you for sharing the sample file.
The sat files contains references to subtypes. Currently there is a bug in building up the ref-table. So that sometimes there can be endless loops.
I'm working on it but can't find a correct implementation.
As a workaround I will simple try to detect and break these "self-references".
-Jens

**Comment by markol** [comment]
I agree that more investigation is needed for that case. Any workaround I have tried, results in surface being omitted in imported solid.

**Comment by jmplonka** [comment]
The omitted surfaces should now be fixed.

**Comment by jmplonka** [comment]
Closed: issue fixed, whereas the subtype table for surfaces is nevertheless incomplete.
