### ISSUE TITLE
Importing sketches with splines

### ISSUE THREAD

**Issue by hugomilan** [jmplonka/InventorLoader#15]
Hi,
First, thanks for such a great plug-in. The installation went smoothly and I could get it to work on my inventor files that had sketches based on semi-circles and lines. However, when I tried to import sketches that were entirely based on splines, the "nativ" conversions did not work (SAT conversion worked but I need "nativ" to be able to edit the sketch). When I imported the sketch, it shows up as empty (the same is true if I import a part that is based on sketches with splines). Any advice?

**Comment by jmplonka** [comment]
Hello,
glad to hear that installation went smoothly :)
When I started this plugin B-Splines weren't available in FreeCAD (v0.16) so I stopped at this point and started working on importing SAT and STEP import. But these that doesn't have the sketches.
Meanwhile v0.17 is available and offers creating of B-Splines.
So please stay tuned as I will incorporate B-Splines next...
I will close this issue when this point is supported.
-Jens

**Comment by hugomilan** [comment]
Thanks for letting me know, Jens. I'll keep an eye on this post.
Regards.

**Comment by jmplonka** [comment]
Can you please check out, if the B-Splines are now shown correctly?
If something is wrong, please provide me with an example if possible.

**Comment by hugomilan** [comment]
Thanks. It imported something but not the correct geometry.
Sure, I can send you some geometries, but privately. Please, get in touch with me by e-mail hugofernando@gmail.com
Thanks

**Comment by jmplonka** [comment]
Thanks for sharing the example. Please check out the actual result now.
When importing in FreeCAD please make "Extrusão1_Join" visible!
There is an exception caused by an error in Cell "y1010" -> will fix it later.

**Comment by jmplonka** [comment]
There seems to be 2 problems for FreeCAD:
a) 100 sections seems to too much for the Loft feature.
b) The dimension constraint in Section "y1010" seems to be redundant for some reason.

**Comment by hugomilan** [comment]
Hi,
Thanks again for working on that! I believe everything is working now.

The current limitation would be the Loft feature, which Freecad does not seem to handle as Inventor was handling. Anyway, that is a separated issue.
