### ISSUE TITLE
Logo for this workbemch

### ISSUE THREAD

**Issue by luzpaz** [jmplonka/InventorLoader#18]
Ref: https://www.freecadweb.org/wiki/Template:DevWorkbenches
Does it also have a page on the wiki? If so please add it to https://www.freecadweb.org/wiki/External_workbenches

**Comment by jmplonka** [comment]
BTW: InventorLoader is a plugin - not a workbench. It comes with no additional UI.
I can't see any need for an icon, but there's already one in ./Resources/icons/InventorImporter.svg
Until now it has no wiki page right now that could be added to FC's  external workbenches page (because it is no workbench).

**Comment by luzpaz** [comment]
Good point, though we need to represent it somehow. We'll add it to the wiki page with a notation about the discrepency

**Comment by luzpaz** [comment]
@jmplonka We still need a way to represent your plugin in the Addon Manager and wiki. I see there is a https://github.com/jmplonka/InventorLoader/blob/master/Resources/icons/InventorImporter.svg 
I could also post on the FC UI/UX subforum to see if anyone wants to create a logo for this...or do you prefer to roll your own? what do you think ?

**Comment by jmplonka** [comment]
There is one Point, that might be worth to be available in FreeCAD that is a common feature in Autodesk Inventor: "iParts"
With iParts you are able to define a set of variations of a model. The values are held in a table. An iPart defines a set of parameters that are differently set by each variant model.
With this Feature InventorLoader would be more like a WorkBench than.
ps: Any support, that will be offered to me, is highly appreciated.

**Comment by jmplonka** [comment]
Well, finally InventorLoader got it's Workbench with "Inventor" menu and toolbars for:
* [create new objects](../wiki/Toolbar-Create)
* [modify existing objects](../wiki/Toolbar-Modify)
* [modify surfaces](../wiki/Toolbar-Surface)
* [apply patterns](../wiki/Toolbar-Patterns)
* [handle Sheet-Metal](../wiki/Toolbar-SheetMetal)
* [handle Plastic](../wiki/Toolbar-Plastic)

I've also added a page for each already available features. Some of the features will obviously simply run the functionality other workbenches offers (e.g. extrude, revolve, ...)

You've asked for an [icon](../blob/master/Resources/icons/Inventor-WB.svg) - does it meets the requirements?
