### ISSUE TITLE
Report version of Autodesk - Not supported.

### ISSUE THREAD

**Issue by KeithSloan** [jmplonka/InventorLoader#31]
Re Issue #29 - Please could you update the code to check for supported file version and if not report and exit the importer cleanly, rather than lots of error messages as per issue #29

**Comment by jmplonka** [comment]
A messagebox is now shown with the version of inventor, the file was saved.

**Comment by jmplonka** [comment]
@luzpaz: the corresponding commit was https://github.com/jmplonka/InventorLoader/tree/cda7a80671a26795487ead9a1dc33dd1b07f4bc7
