### ISSUE TITLE
Fusion 360 Workflow

### ISSUE THREAD

**Issue by infosisio** [jmplonka/InventorLoader#45]
According to the description, only parts can be imported and not assemblies.

For the case of fusion 360, this means manually exporting each part to a separate f3d file?

I assume there is no option to automatically extract all the parts of a fusion 360 assembly?

Is assembly support on the nearby horizon?

**Comment by infosisio** [comment]
I've tried importing several F3D files and chose native but it doesn't include the features, only solids.

Is this going to be supported soon?

**Comment by jmplonka** [comment]
Hi, currently I'm working on it :)
Unfortunately this was released with one of the lasts submits.
