### ISSUE TITLE
Some errors were found that prevent to install this workbench: Some errors were found that prevent to install this workbench. Please install the missing components first.

### ISSUE THREAD

**Issue by poulet67** [jmplonka/InventorLoader#47]
I keep getting this error on a fresh Freecad Install (0.19) on Windows 10 when trying to install from the Addon Manager.

**Comment by jmplonka** [comment]
Please, can you please send me the text in the output window, because I've no Idea about what is going wrong.
What OS (Linux, OS-X, Windows) are you using?

**Comment by MariwanJ** [comment]
Some errors were found that prevent to install this workbench: Some errors were found that prevent to install this workbench. Please install the missing components first.

**Comment by luzpaz** [comment]
@MariwanJ TBF current HEAD is at 25310 and you're using 24840

**Comment by MariwanJ** [comment]
Ohh! . so long time I was only focusing on my learning/making the new tools :).
I will update my freecad.

**Comment by eflukx** [comment]
Same issue here. Was this resolved in the mean time?
No clue what dependencies might be missing. Need to dig up a proper log somewhere, the output in the FreeCAD GUI isn't of much help...

**Comment by luzpaz** [comment]
The FreeCAD Addon Manger has been updated in v0.20 significantly. Please install the latest (nightly) development version and test installing this addon "InventorLoader" to see if the Addon Manager does indeed install all dependencies accordingly

**Comment by poulet67** [comment]
It works great now! Thank you so much!
