### ISSUE TITLE
Update to new FreeCAD AddonManager metadata schema

### ISSUE THREAD

**Issue by luzpaz** [jmplonka/InventorLoader#54]
https://github.com/FreeCAD/FreeCAD-addons/issues/200

**Comment by luzpaz** [comment]
@jmplonka ping

**Comment by luzpaz** [comment]
https://github.com/jmplonka/InventorLoader/blob/master/metadata.txt needs to be migrated to `package.xml` and modified

**Comment by jmplonka** [comment]
Done - plaese, check if valid.

**Comment by luzpaz** [comment]
@jmplonka in the meanwhile the `metadata.txt` file can be removed :wink:

**Comment by chennes** [comment]
@luzpaz actually that's not true, you want to keep that around for the 
```
[dependencies]
workbenches=Part,Draft,Sketcher
pylibs=olefile,xlrd,xlwt,xlutils
FCaddon=sheetmetal
```

The rest of it is ignored, but the Python deps are still read from either `requirements.txt` or `metadata.txt`. And yes, the Addon Manager will offer to install the missing dependencies, as long as they are on the approved list. I'll look at adding these.

**Comment by luzpaz** [comment]
https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/AddonManager/ALLOWED_PYTHON_PACKAGES.txt FTW!

**Comment by chennes** [comment]
Oh yeah, right! This WB was one of my test cases, of course the deps already work. I totally forgot.

**Comment by luzpaz** [comment]
Fixed in #55  
~@chennes having an issue loading the InventorLoader in the addon manager. It's looking for a `main` branch when the default is `master`~
![image](https://user-images.githubusercontent.com/4140247/154530011-51d149a7-d53b-4a82-97c7-4d847596cfeb.png)

```
OS: Ubuntu Core 20 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27571 (Git)
Build type: Release
Branch: master
Hash: 0bbc253ddee6801770c78e011c5201b7c2c36080
Python 3.8.10, Qt 5.15.3, Coin 4.0.0, OCC 7.5.2
Locale: English/United States (en_US)
Installed mods: 
  * ToolbarStyle
  * stickframe
  * sheetmetal 0.2.49
  * Behave-Dark-Colors 0.0.1
  * Curves 0.3.0
  * Ship
  * BIM 2021.12.0
```

**Comment by luzpaz** [comment]
Can this be closed?

**Comment by jmplonka** [comment]
Who can tell? Yes from my side :)

**Comment by luzpaz** [comment]
@chennes can we close this?

**Comment by chennes** [comment]
Yes, InventorLoader's metadata seems fine, it displays and installs without issue, including its stated dependencies.
