### ISSUE TITLE
xlutils has been archived

### ISSUE THREAD

**Issue by wavexx** [jmplonka/InventorLoader#62]
Just FIY, while attempting to package this I noticed https://github.com/python-excel/xlutils has been archived/deprecated for a while, with the suggestion to use openpyxl instead (not sure if openpyxl contains everything which is needed by InventorLoader).

**Comment by luzpaz** [comment]
@jmplonka :point_up_2:

**Comment by luzpaz** [comment]
#49 is another dependency that has been deprecrated

**Comment by jmplonka** [comment]
But openpyxl only allows me to read XLSX files not XLS files. So this is no option.

**Comment by wavexx** [comment]
But then https://github.com/python-excel/xlrd is probably the second best alternative which is often used along openpyxl.

**Comment by jmplonka** [comment]
BTW: xlrd, xlwt and xlutils belongs together...
