### ISSUE TITLE
What can be extended in FreeCAD to accomodate this importer?

### ISSUE THREAD

**Issue by luzpaz** [jmplonka/InventorLoader#7]
You mention that FC can only read a few iProperties. Is this something that could be coded in FC or is it proprietary? Any other examples?

**Comment by jmplonka** [comment]
until now I didn't find a way to transfer all the iProperties into the properties FC supports.
Any hint?

**Comment by luzpaz** [comment]
@jmplonka please ask on the forums, i'm sure the community can offer good solutions.

**Comment by jmplonka** [comment]
Thanks - let's see for the solutions...
